pipeline {
    agent any
    environment {
        APPLICATION_NAME = 'gboex-automationtest-portalintegracao'
        SOLUTION = 'gboex-automationtest-portalintegracao-teste-jenkins.sln'                
        
        SLACK_CHANNEL_BUILD = 'jenkins-builds'
        SLACK_CHANNEL_CI = 'jenkins-ci'
        ENV_NAME = ''
        CI_DIR = ''
        CHROMEDRIVER_VERSION = '123.0.6312.5800'
    }
    stages {           
        stage('restore') {
            steps {
                bat "dotnet clean ${env.SOLUTION}"
                bat "dotnet restore ${env.SOLUTION}"
            }
        }
        stage('build') {
           steps {               
               bat "dotnet build -c Debug --no-restore ${env.SOLUTION}"
            }
        }
        stage('run tests') {
            steps {
                bat "set PATH=C:\\chromedriver\\${env.CHROMEDRIVER_VERSION};%PATH%"
                bat "dotnet test --no-restore"
            }
        }
        stage('generate allure report') {
            steps {
                allure commandline: 'Allure', 
                includeProperties: false, 
                jdk: '', 
                report: 'gboex-automationtest-portalintegracao\\bin\\Debug\\net6.0\\allure-report', 
                results: [[path: 'gboex-automationtest-portalintegracao\\bin\\Debug\\net6.0\\allure-results']]
            }
        }
    }
}